version: "3.8"
services:
  backend:
    build: ./taskAuthApi
    container_name: tarefas-backend
    ports:
      - "8001:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TarefasDb;User=sa;Password=SenhaForte123;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    networks:
      - tarefas-network
  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: tarefas-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SenhaForte123
    ports:
      - "1433:1433"
    networks:
      - tarefas-network

networks:
  tarefas-network:
